name: Vuejs
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
      - name: Npm install & npm build
        run: |
          npm install
          npm run build
